services:
  gateway:
    container_name: gateway-service
    build:
      context: .
      args:
        - APP=gateway
      target: ${NODE_ENV}
    command: pnpm run start:debug gateway
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - network

  order:
    container_name: order-service
    build:
      context: .
      args:
        - APP=order
      target: ${NODE_ENV}
    command: pnpm run start:debug order
    ports:
      - 50051:50051
      - 9230:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - network

  product:
    container_name: product-service
    build:
      context: .
      args:
        - APP=product
      target: ${NODE_ENV}
    command: pnpm run start:debug product
    ports:
      - 50052:50052
      - 9231:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - network

  payment:
    container_name: payment-service
    build:
      context: .
      args:
        - APP=payment
      target: ${NODE_ENV}
    command: pnpm run start:debug payment
    ports:
      - 50053:50053
      - 9232:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - network

networks:
  network:
